version: '3'

services:
  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "8000:80"
    networks:
      - task-management-network

networks:
  task-management-network:
    external: true 