version: '3.8'

services:
  group-service:
    build: .
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host:5432/taskmanagement
    volumes:
      - ./app:/app
    restart: unless-stopped
    extra_hosts:
      - "host:host-gateway"
