version: '3.8'

services:
  group-service:
    build: .
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@task-management-postgres:5432/postgres
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    extra_hosts:
      - "host:host-gateway"
    networks:
      - task-management-network
      - default

networks:
  task-management-network:
    external: true
