# docker-compose -f services/auth-service/docker-compose.yml up -d

version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host:5432/taskmanagement
    volumes:
      - ./app:/app
    restart: unless-stopped
    extra_hosts:
      - "host:host-gateway"