# docker-compose -f services/auth-service/docker-compose.yml up -d

version: '3.8'

services:
  auth-service:
    container_name: auth-service
    build: .
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@host:5432/task_management_db
      - PYTHONPATH=/app
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py
    restart: unless-stopped
    extra_hosts:
      - "host:host-gateway"
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]